/// <reference types="cypress-xpath" />
/// <reference types= "cypress" />


describe('AgendamentoSimples', () => {
    beforeEach(() => {
        cy.visit('/')
    })
    it('Agendamento Parceria Particular', () => {
        cy.get('#E-mail')
            .type('roger.mazzali@amorsaude.com')
        cy.get('#Senha')
            .type('Rrm@amor202')
        cy.get('#login')
            .click()
        cy.contains('span', ' Telemedicina ')
            .should('be.visible')
            .click()
        cy.get('#EntrarUnidade')
            .click()
        cy.get('#schedule')
            .click()
        cy.wait(1000)  //should('be.visible', { timeout: 6000 }) // Espera mais tempo para aparecer
        cy.contains('span', 'Agendar atendimento')
            .should('be.visible')
            .should('exist')
            .click()
        cy.wait(1000)
        cy.get('mat-select[formcontrolname="expertiseAreas"]')
            .click()
        cy.contains('span', 'Acupuntura')
            .click()
        cy.get('mat-select[formcontrolname="professionals"]')
            .click()
        cy.contains('span', ' Dr. Profissional Teste Suporte ')
            .click()
        cy.contains('span', ' Pesquisar ')
            .should('be.visible')
            .click()
        const today = new Date()
        const weekDay = today.getDay()
        cy.get('.cal-day-columns .cal-day-column') //Filtra apenas os dias
            .eq(weekDay)
            .find('.livre')
            .first()
            .click()
        cy.get('#cpf')
            .type('792.958.688-03')
            .should('have.value', '792.958.688-03')
        cy.wait(1000)
        cy.get('mat-select[formcontrolname="originChannel"]')
            .click()
            .wait(2000)
        cy.contains('span', 'Email')
            .scrollIntoView()
            .should('be.visible')
            .click()
        cy.contains('button', ' + Incluir procedimento ')
            .click()
        cy.get('mat-select[id="AdProcedimento"]')
            .click()
        cy.contains('span', 'Teleconsulta especialidades')
            .click()
        cy.wait(1000)
        cy.contains('button', ' Adicionar ')
            .click()
        cy.wait(1000)
        cy.contains('button', ' Confirmar ')
            .click()
        cy.get('button')
            .contains('Ok')
            .click()

    })

    it('Agendamento Parceria Cartão de Todos', () => {
        cy.get('#E-mail')
            .type('roger.mazzali@amorsaude.com')
        cy.get('#Senha')
            .type('Rrm@amor202')
        cy.get('#login')
            .click()
        cy.contains('span', ' Telemedicina ')
            .should('be.visible')
            .click()
        cy.get('#EntrarUnidade')
            .click()
        cy.get('#schedule')
            .click()
        cy.wait(1000)  //should('be.visible', { timeout: 6000 }) // Espera mais tempo para aparecer
        cy.contains('span', 'Agendar atendimento')
            .should('be.visible')
            .should('exist')
            .click()
        cy.wait(1000)
        cy.get('mat-select[formcontrolname="expertiseAreas"]')
            .click()
        cy.contains('span', 'Acupuntura')
            .click()
        cy.get('mat-select[formcontrolname="professionals"]')
            .click()
        cy.contains('span', ' Dr. Profissional Teste Suporte ')
            .click()
        cy.contains('span', ' Pesquisar ')
            .should('be.visible')
            .click()
        const today = new Date()
        const weekDay = today.getDay()
        cy.get('.cal-day-columns .cal-day-column') //Filtra apenas os dias
            .eq(weekDay)
            .find('.livre')
            .first()
            .click()
        cy.get('#cpf')
            .type('436.577.728-98')
            .should('have.value', '436.577.728-98')
        cy.wait(1000)
        cy.get('mat-select[formcontrolname="originChannel"]')
            .click()
            .wait(2000)
        cy.contains('span', 'Email')
            .scrollIntoView()
            .should('be.visible')
            .click()
        cy.contains('button', ' + Incluir procedimento ')
            .click()
        cy.get('mat-select[id="AdProcedimento"]')
            .click()
        cy.contains('span', 'Teleconsulta especialidades')
            .click()
        cy.wait(1000)
        cy.contains('button', ' Adicionar ')
            .click()
        cy.wait(1000)
        cy.contains('button', ' Confirmar ')
            .click()
        cy.get('button')
            .contains('Ok')
            .click()

    })
}) //Finalizado

describe('AgendamentoPorEncaixe', () => {
    beforeEach(() => {
        cy.visit('/')
    })
    it('AgendamentoPorEncaixeSimples', () => {
        cy.get('#E-mail')
            .type('roger.mazzali@amorsaude.com')
        cy.get('#Senha')
            .type('Rrm@amor202')
        cy.get('#login')
            .click()
        cy.contains('span', ' Telemedicina ')
            .should('be.visible')
            .click()
        cy.get('#EntrarUnidade')
            .click()
        cy.get('#schedule')
            .click()
        cy.wait(1000)  //should('be.visible', { timeout: 6000 }) // Espera mais tempo para aparecer
        cy.contains('span', 'Agendar atendimento')
            .should('be.visible')
            .should('exist')
            .click()
        cy.wait(1000)
        cy.get('mat-select[formcontrolname="expertiseAreas"]')
            .click()
        cy.contains('span', 'Acupuntura')
            .click()
        cy.get('mat-select[formcontrolname="professionals"]')
            .click()
        cy.contains('span', ' Dr. Profissional Teste Suporte ')
            .click()
        cy.contains('span', ' Pesquisar ')
            .should('be.visible')
            .click()
        cy.get('button')
            .contains(' Criar encaixe ')
            .click()
        cy.wait(1000)
        const data = new Date() //Cria um objeto do tipo data
        // Obtém o ano, mês e dia
        const ano = data.getFullYear()
        const mes = String(data.getMonth() + 1).padStart(2, '0') // O mês é 0-indexado, por isso somamos 1 e garantimos 2 dígitos
        const dia = String(data.getDate()).padStart(2, '0'); // Garantimos que o dia tenha 2 dígitos
        const dataFormatada = `${ano}-${mes}-${dia}` // Formata a data no formato YYYY/MM/DD
        cy.get('input[formcontrolname="date"]')
            .type(dataFormatada)

        cy.wait(1000)
        const dataTime = new Date()
        const hora = String(dataTime.getHours()).padStart(2, '0') // Obtém a hora (0-23)
        const minuto = String(dataTime.getMinutes() + 2).padStart(2, '0') // Obtém o minuto (0-59) // Adiciona 2 minutos à hora atual
        const horaFormatada = `${hora}:${minuto}`
        cy.get('input[formcontrolname="time"]')
            .type(horaFormatada)
        cy.wait(1000)
        cy.get('#cpf')
            .type('792.958.688-03')
            .should('have.value', '792.958.688-03')
        cy.wait(1000)
        cy.get('mat-select[formcontrolname="originChannel"]')
            .click()
            .wait(2000)
        cy.contains('span', 'Email')
            .scrollIntoView()
            .should('be.visible')
            .click()
        cy.contains('button', ' + Incluir procedimento ')
            .click()
        cy.get('mat-select[id="AdProcedimento"]')
            .click()
        cy.contains('span', 'Teleconsulta especialidades')
            .click()
        cy.wait(1000)
        cy.contains('button', ' Adicionar ')
            .click()
        cy.wait(1000)
        cy.contains('button', ' Confirmar ')
            .click()
        cy.get('button')
            .contains('Ok')
            .click()
    })
}) //Em construção

describe('Reagendamento', () => {
    beforeEach(() => {
        cy.visit('/')
    })
    it('Agendamento Parceria Particular', () => {
        cy.get('#E-mail')
            .type('roger.mazzali@amorsaude.com')
        cy.get('#Senha')
            .type('Rrm@amor202')
        cy.get('#login')
            .click()
        cy.contains('span', ' Telemedicina ')
            .should('be.visible')
            .click()
        cy.get('#EntrarUnidade')
            .click()
        cy.get('#schedule')
            .click()
        cy.wait(1000)  //should('be.visible', { timeout: 6000 }) // Espera mais tempo para aparecer
        cy.contains('span', 'Agendar atendimento')
            .should('be.visible')
            .should('exist')
            .click()
        cy.wait(1000)
        cy.get('mat-select[formcontrolname="expertiseAreas"]')
            .click()
        cy.contains('span', 'Acupuntura')
            .click()
        cy.get('mat-select[formcontrolname="professionals"]')
            .click()
        cy.contains('span', ' Dr. Profissional Teste Suporte ')
            .click()
        cy.contains('span', ' Pesquisar ')
            .should('be.visible')
            .click()
        const today = new Date()
        const weekDay = today.getDay()
        cy.get('.cal-day-columns .cal-day-column') //Filtra apenas os dias
            .eq(weekDay)
            .find('.livre')
            .first()
            .click()
        cy.get('#cpf')
            .type('792.958.688-03')
            .should('have.value', '792.958.688-03')
        cy.wait(1000)
        cy.get('mat-select[formcontrolname="originChannel"]')
            .click()
            .wait(2000)
        cy.contains('span', 'Email')
            .scrollIntoView()
            .should('be.visible')
            .click()
        cy.contains('button', ' + Incluir procedimento ')
            .click()
        cy.get('mat-select[id="AdProcedimento"]')
            .click()
        cy.contains('span', 'Teleconsulta especialidades')
            .click()
        cy.wait(1000)
        cy.contains('button', ' Adicionar ')
            .click()
        cy.wait(1000)
        cy.contains('button', ' Confirmar ')
            .click()
        cy.get('button')
            .contains('Ok')
            .click()

    })
    it('Cancelamento de agenda do profissional', () => {
        cy.get('#E-mail')
            .type('roger.mazzali@amorsaude.com')
        cy.get('#Senha')
            .type('Rrm@amor202')
        cy.get('#login')
            .click()
        cy.contains('span', ' Telemedicina ')
            .should('be.visible')
            .click()
        cy.get('#EntrarUnidade')
            .click()
        cy.get('#schedule')
            .click()
        cy.wait(1000)  //should('be.visible', { timeout: 6000 }) // Espera mais tempo para aparecer
        cy.contains('span', 'Agendar atendimento')
            .should('be.visible')
            .should('exist')
            .click()
        cy.wait(1000)
        cy.get('mat-select[formcontrolname="expertiseAreas"]')
            .click()
        cy.contains('span', 'Acupuntura')
            .click()
        cy.get('mat-select[formcontrolname="professionals"]')
            .click()
        cy.contains('span', ' Dr. Profissional Teste Suporte ')
            .click()
        cy.contains('span', ' Pesquisar ')
            .should('be.visible')
            .click()
        const today = new Date()
        const weekDay = today.getDay()
        cy.get('.cal-day-columns .cal-day-column') //Filtra apenas os dias
            .eq(weekDay)
            .find('.agendado ', { timeout: 2000 })
            .first()
            .click()
        cy.get('button[title="Reagendar"]')
            .click()
        cy.get('.mat-select') // Seleciona a tela do reagendamento
            .eq(6)
            .click()
        cy.contains('span', ' Cancelamento de agenda do profissional ')
            .click()
        cy.get('button')
            .contains(' Prosseguir ')
            .click()
        const today2 = new Date()
        const weekDay2 = today2.getDay()
        cy.get('.cal-day-columns .cal-day-column')
            .eq(weekDay2)
            .find('.livre ', { timeout: 2000 })
            .first()
            .click()
        cy.get('button')
            .contains(' Reagendar ')
            .click()
        cy.get('app-reschedule-appointment-resume-modal').within(() => {
            cy.get('h3').should('have.text', 'Reagendamento realizado com sucesso')
        })
        cy.wait(2000)
        cy.get('button')
            .contains(' Voltar ')
            .should('be.visible')
            .click()
    })
    it('Outros não especificado', () => {
        cy.get('#E-mail')
            .type('roger.mazzali@amorsaude.com')
        cy.get('#Senha')
            .type('Rrm@amor202')
        cy.get('#login')
            .click()
        cy.contains('span', ' Telemedicina ')
            .should('be.visible')
            .click()
        cy.get('#EntrarUnidade')
            .click()
        cy.get('#schedule')
            .click()
        cy.wait(1000)  //should('be.visible', { timeout: 6000 }) // Espera mais tempo para aparecer
        cy.contains('span', 'Agendar atendimento')
            .should('be.visible')
            .should('exist')
            .click()
        cy.wait(1000)
        cy.get('mat-select[formcontrolname="expertiseAreas"]')
            .click()
        cy.contains('span', 'Acupuntura')
            .click()
        cy.get('mat-select[formcontrolname="professionals"]')
            .click()
        cy.contains('span', ' Dr. Profissional Teste Suporte ')
            .click()
        cy.contains('span', ' Pesquisar ')
            .should('be.visible')
            .click()
        const today = new Date()
        const weekDay = today.getDay()
        cy.get('.cal-day-columns .cal-day-column') //Filtra apenas os dias
            .eq(weekDay)
            .find('.agendado ', { timeout: 2000 })
            .first()
            .click()
        cy.get('button[title="Reagendar"]')
            .click()
        cy.get('.mat-select')
            .eq(6)
            .click()
        cy.contains('span', ' Outros não especificado ')
            .click()
        cy.get('button')
            .contains(' Prosseguir ')
            .click()
        const today2 = new Date()
        const weekDay2 = today2.getDay()
        cy.get('.cal-day-columns .cal-day-column')
            .eq(weekDay2)
            .find('.livre ', { timeout: 2000 })
            .first()
            .click()
        cy.get('button')
            .contains(' Reagendar ')
            .click()
        cy.get('app-reschedule-appointment-resume-modal').within(() => {
            cy.get('h3').should('have.text', 'Reagendamento realizado com sucesso')
        })
        cy.wait(2000)
        cy.get('button')
            .contains(' Voltar ')
            .should('be.visible')
            .click()

    })
    it('Paciente não compareceu e deseja remarcação', () => {
        cy.get('#E-mail')
            .type('roger.mazzali@amorsaude.com')
        cy.get('#Senha')
            .type('Rrm@amor202')
        cy.get('#login')
            .click()
        cy.contains('span', ' Telemedicina ')
            .should('be.visible')
            .click()
        cy.get('#EntrarUnidade')
            .click()
        cy.get('#schedule')
            .click()
        cy.wait(1000)  //should('be.visible', { timeout: 6000 }) // Espera mais tempo para aparecer
        cy.contains('span', 'Agendar atendimento')
            .should('be.visible')
            .should('exist')
            .click()
        cy.wait(1000)
        cy.get('mat-select[formcontrolname="expertiseAreas"]')
            .click()
        cy.contains('span', 'Acupuntura')
            .click()
        cy.get('mat-select[formcontrolname="professionals"]')
            .click()
        cy.contains('span', ' Dr. Profissional Teste Suporte ')
            .click()
        cy.contains('span', ' Pesquisar ')
            .should('be.visible')
            .click()
        const today = new Date()
        const weekDay = today.getDay()
        cy.get('.cal-day-columns .cal-day-column') //Filtra apenas os dias
            .eq(weekDay)
            .find('.agendado ', { timeout: 2000 })
            .first()
            .click()
        cy.get('button[title="Reagendar"]')
            .click()
        cy.get('.mat-select')
            .eq(6)
            .click()
        cy.contains('span', ' Paciente não compareceu e deseja remarcação ')
            .click()
        cy.get('button')
            .contains(' Prosseguir ')
            .click()
        const today2 = new Date()
        const weekDay2 = today2.getDay()
        cy.get('.cal-day-columns .cal-day-column')
            .eq(weekDay2)
            .find('.livre ', { timeout: 2000 })
            .first()
            .click()
        cy.get('button')
            .contains(' Reagendar ')
            .click()
        cy.get('app-reschedule-appointment-resume-modal').within(() => {
            cy.get('h3').should('have.text', 'Reagendamento realizado com sucesso')
        })
        cy.wait(2000)
        cy.get('button')
            .contains(' Voltar ')
            .should('be.visible')
            .click()
    })
    it('Problemas de conexão', () => {
        cy.get('#E-mail')
            .type('roger.mazzali@amorsaude.com')
        cy.get('#Senha')
            .type('Rrm@amor202')
        cy.get('#login')
            .click()
        cy.contains('span', ' Telemedicina ')
            .should('be.visible')
            .click()
        cy.get('#EntrarUnidade')
            .click()
        cy.get('#schedule')
            .click()
        cy.wait(1000)  //should('be.visible', { timeout: 6000 }) // Espera mais tempo para aparecer
        cy.contains('span', 'Agendar atendimento')
            .should('be.visible')
            .should('exist')
            .click()
        cy.wait(1000)
        cy.get('mat-select[formcontrolname="expertiseAreas"]')
            .click()
        cy.contains('span', 'Acupuntura')
            .click()
        cy.get('mat-select[formcontrolname="professionals"]')
            .click()
        cy.contains('span', ' Dr. Profissional Teste Suporte ')
            .click()
        cy.contains('span', ' Pesquisar ')
            .should('be.visible')
            .click()
        const today = new Date()
        const weekDay = today.getDay()
        cy.get('.cal-day-columns .cal-day-column') //Filtra apenas os dias
            .eq(weekDay)
            .find('.agendado ', { timeout: 2000 })//Começar com uma classe .livre
            .first()
            .click()
        cy.contains('button', ' Reagendar ') // Verificar o botão "Reagendar"
            .then(($button) => { //Captura o botão encontrado
                // Verifica se o botão está visível e habilitado
                if ($button.is(':visible') && !$button.attr('disabled')) {
                    cy.contains('button', ' Reagendar ').click() // 'Botão de Reagendar está visível e habilitado. Realizando o clique.'
                    cy.get('.mat-select')
                        .eq(6)
                        .click()
                    cy.contains('span', ' Problemas de conexão ')
                        .click()
                    cy.get('button')
                        .contains(' Prosseguir ')
                        .click()
                    const today2 = new Date()
                    const weekDay2 = today2.getDay()
                    cy.get('.cal-day-columns .cal-day-column')
                        .eq(weekDay2)
                        .find('.livre ', { timeout: 2000 })
                        .first()
                        .click()
                    cy.get('button')
                        .contains(' Reagendar ')
                        .click()
                    cy.get('app-reschedule-appointment-resume-modal').within(() => {
                        cy.get('h3').should('have.text', 'Reagendamento realizado com sucesso')
                    })
                    cy.wait(2000)
                    cy.get('button')
                        .contains(' Voltar ')
                        .should('be.visible')
                        .click()
                } else {
                    cy.contains('button', ' Cancelar ').click()
                    cy.log('Botão de Reagendar não está disponível. Saindo da página')
                }
            })
    })

    it.skip('Transferência em massa', () => {
        cy.get('#E-mail')
            .type('roger.mazzali@amorsaude.com')
        cy.get('#Senha')
            .type('Rrm@amor202')
        cy.get('#login')
            .click()
        cy.contains('span', ' Telemedicina ')
            .should('be.visible')
            .click()
        cy.get('#EntrarUnidade')
            .click()
        cy.get('#schedule')
            .click()
        cy.wait(1000)  //should('be.visible', { timeout: 6000 }) // Espera mais tempo para aparecer
        cy.contains('span', 'Agendar atendimento')
            .should('be.visible')
            .should('exist')
            .click()
        cy.wait(1000)
        cy.get('mat-select[formcontrolname="expertiseAreas"]')
            .click()
        cy.contains('span', 'Acupuntura')
            .click()
        cy.get('mat-select[formcontrolname="professionals"]')
            .click()
        cy.contains('span', ' Dr. Profissional Teste Suporte ')
            .click()
        cy.contains('span', ' Pesquisar ')
            .should('be.visible')
            .click()
        const today = new Date()
        const weekDay = today.getDay()
        cy.get('.cal-day-columns .cal-day-column') //Filtra apenas os dias
            .eq(weekDay)
            .find('.agendado ', { timeout: 2000 })
            .eq(1)
            .click()
        cy.get('button[title="Reagendar"]')
            .click()
        cy.get('.mat-select')
            .eq(6)
            .click()
        cy.contains('span', ' Transferência em massa ')
            .click()
        cy.get('button')
            .contains(' Prosseguir ')
            .click()
        const today2 = new Date()
        const weekDay2 = today2.getDay()
        cy.get('.cal-day-columns .cal-day-column')
            .eq(weekDay2)
            .find('.livre ', { timeout: 2000 })
            .first()
            .click()
        cy.get('button')
            .contains(' Reagendar ')
            .click()
        cy.get('app-reschedule-appointment-resume-modal').within(() => {
            cy.get('h3').should('have.text', 'Reagendamento realizado com sucesso')
        })
        cy.wait(2000)
        cy.get('button')
            .contains(' Voltar ')
            .should('be.visible')
            .click()
    })
}) //Finalizado

describe('Validando Regra dos 3 Reagendamentos', () => {
    beforeEach(() => {
        cy.visit('/')
    })
    
    it('Agendamento Parceria Particular', () => {
        cy.get('#E-mail')
            .type('roger.mazzali@amorsaude.com')
        cy.get('#Senha')
            .type('Rrm@amor202')
        cy.get('#login')
            .click()
        cy.contains('span', ' Telemedicina ')
            .should('be.visible')
            .click()
        cy.get('#EntrarUnidade')
            .click()
        cy.get('#schedule')
            .click()
        cy.wait(1000)  //should('be.visible', { timeout: 6000 }) // Espera mais tempo para aparecer
        cy.contains('span', 'Agendar atendimento')
            .should('be.visible')
            .should('exist')
            .click()
        cy.wait(1000)
        cy.get('mat-select[formcontrolname="expertiseAreas"]')
            .click()
        cy.contains('span', 'Acupuntura')
            .click()
        cy.get('mat-select[formcontrolname="professionals"]')
            .click()
        cy.contains('span', ' Dr. Profissional Teste Suporte ')
            .click()
        cy.contains('span', ' Pesquisar ')
            .should('be.visible')
            .click()
        const today = new Date()
        const weekDay = today.getDay()
        cy.get('.cal-day-columns .cal-day-column') //Filtra apenas os dias
            .eq(weekDay)
            .find('.livre')
            .first()
            .click()
        cy.get('#cpf')
            .type('792.958.688-03')
            .should('have.value', '792.958.688-03')
        cy.wait(1000)
        cy.get('mat-select[formcontrolname="originChannel"]')
            .click()
            .wait(2000)
        cy.contains('span', 'Email')
            .scrollIntoView()
            .should('be.visible')
            .click()
        cy.contains('button', ' + Incluir procedimento ')
            .click()
        cy.get('mat-select[id="AdProcedimento"]')
            .click()
        cy.contains('span', 'Teleconsulta especialidades')
            .click()
        cy.wait(1000)
        cy.contains('button', ' Adicionar ')
            .click()
        cy.wait(1000)
        cy.contains('button', ' Confirmar ')
            .click()
        cy.get('button')
            .contains('Ok')
            .click()

    })

    const testCases = ['Caso 1', 'Caso 2', 'Caso 3', 'Caso 4'];
    testCases.forEach((testCase) => {
        it(`Executando o teste para ${testCase}`, () => {
            cy.get('#E-mail')
                .type('roger.mazzali@amorsaude.com')
            cy.get('#Senha')
                .type('Rrm@amor202')
            cy.get('#login')
                .click()
            cy.contains('span', ' Telemedicina ')
                .should('be.visible')
                .click()
            cy.get('#EntrarUnidade')
                .click()
            cy.get('#schedule')
                .click()
            cy.wait(1000)  //should('be.visible', { timeout: 6000 }) // Espera mais tempo para aparecer
            cy.contains('span', 'Agendar atendimento')
                .should('be.visible')
                .should('exist')
                .click()
            cy.wait(1000)
            cy.get('mat-select[formcontrolname="expertiseAreas"]')
                .click()
            cy.contains('span', 'Acupuntura')
                .click()
            cy.get('mat-select[formcontrolname="professionals"]')
                .click()
            cy.contains('span', ' Dr. Profissional Teste Suporte ')
                .click()
            cy.contains('span', ' Pesquisar ')
                .should('be.visible')
                .click()
            const today = new Date()
            const weekDay = today.getDay()
            cy.debug()
            cy.get('.cal-day-columns .cal-day-column') //Filtra apenas os dias
                .eq(weekDay)
                .find('.agendado ', { timeout: 2000 })//Começar com uma classe .livre
                .first()
                .click()
            cy.contains('button', ' Reagendar ') // Verificar o botão "Reagendar"
                .then(($button) => { //Captura o botão encontrado
                    // Verifica se o botão está visível e habilitado
                    if ($button.is(':visible') && !$button.attr('disabled')) {
                        cy.contains('button', ' Reagendar ').click() // 'Botão de Reagendar está visível e habilitado. Realizando o clique.'
                        cy.get('.mat-select')
                            .eq(6)
                            .click()
                        cy.contains('span', ' Problemas de conexão ')
                            .click()
                        cy.get('button')
                            .contains(' Prosseguir ')
                            .click()
                        const today2 = new Date()
                        const weekDay2 = today2.getDay()
                        cy.get('.cal-day-columns .cal-day-column')
                            .eq(weekDay2)
                            .find('.livre ', { timeout: 2000 })
                            .first()
                            .click()
                        cy.get('button')
                            .contains(' Reagendar ')
                            .click()
                        cy.get('app-reschedule-appointment-resume-modal').within(() => {
                            cy.get('h3').should('have.text', 'Reagendamento realizado com sucesso')
                        })
                        cy.wait(2000)
                        cy.get('button')
                            .contains(' Voltar ')
                            .should('be.visible')
                            .click()
                    } else {
                        cy.contains('button', ' Cancelar ').click()
                        cy.log('Botão de Reagendar não está disponível. Saindo da página')
                    }
                })
        })
    })
}) //Finalizado

describe('Confirmar agendamento', () => {
    beforeEach(() => {
        cy.visit('/')
    })
    it('Marcado-Confirmado', () => {
        cy.get('#E-mail')
            .type('roger.mazzali@amorsaude.com')
        cy.get('#Senha')
            .type('Rrm@amor202')
        cy.get('#login')
            .click()
        cy.contains('span', ' Telemedicina ')
            .should('be.visible')
            .click()
        cy.get('#EntrarUnidade')
            .click()
        cy.wait(1000)
        cy.get()

    })
}) // Em construção


